### ISSUE TITLE
Any release?

### ISSUE THREAD

**Issue by sedwo** [andrewcox/wireshark-with-thrift-plugin#1]
I'm really eager to try this out within our own Thrift supported app, and it would be great if there was a released version of this build.  (Win32)  For those that don't want to setup the entire dev. environment.

Unless there is an easier way to plug-in a Thrift dissector into the latest Wireshark?

**Comment by andrewcox** [comment]
Two things

1) All our servers run linux, so it's unlikely we'll put effort into a windows build of this.

2) This is actually a pretty old and incomplete wireshark plugin now, a colleague of mine @alandau recently did an overhaul of this work that works a lot better. I'll encourage him to get that open-sourced so you can build from that instead, if you decide to go ahead and setup the dev environment.
